### ISSUE TITLE
Game freezes when attempting to use nomad book

### ISSUE THREAD

**Issue by bubbaryebread** [Ladysnake/Nomad-Books#10]
Maybe it's just my computer, but when I click on a block with my newly crafted nomad book, the game immediately freezes and I have to shut off my computer. I have API downloaded, so idk what the issue would be.

**Comment by doctor4t** [comment]
What version are you on? Do you have a crash log? I suppose no, so maybe you could send the latest log please?

**Comment by bubbaryebread** [comment]
So sorry for not getting back until now, a lot of life has happened. I'm running 1.15.2, with the 0.2.1 file. I don't receive a crash log (not that I am aware of at least, I don't know if it would automatically pop up or if I have to find it), and I'm not sure how to find a log to send. I have to admit I'm not proficient with finding things like that with Minecraft, so I apologize for that.

**Comment by doctor4t** [comment]
Since it did not happen to me once in all of my testing and I haven't had any similar reports I'm assuming this somehow got fixed along the way.
