### ISSUE TITLE
1.15.2 crashes on the dedicated server

### ISSUE THREAD

**Issue by coderbot16** [Ladysnake/Nomad-Books#14]
NomadBookItem calls ItemEntity#getAge on both the client and the dedicated server: https://github.com/Ladysnake/Nomad-Books/blob/master/src/main/java/ladysnake/nomadbooks/common/item/NomadBookItem.java#L376

```java
                            return itemEntity.getAge() < 1;
```

However, the method does not exist on the dedicated server:

```java
    @Environment(EnvType.CLIENT)
    public int getAge() {
        return this.age;
    }
```

Resulting in [this crash](https://hastebin.com/bunajugola.bash)

**Comment by milkev** [comment]
ive gotten the same thing a few times today. only occurs with my friends books but not my own.
[crash-2020-04-07_00.15.48-server.txt](https://github.com/Ladysnake/Nomad-Books/files/4442350/crash-2020-04-07_00.15.48-server.txt)
