### ISSUE TITLE
Fluids (lava) kept on pickup, in both book and 'real world'

### ISSUE THREAD

**Issue by milkev** [Ladysnake/Nomad-Books#16]
if you put lava inside a nomad book, and pick the nomad book up, it will seem like it doesnt pick up the lava. but when you place down the nomad book again there is lava, as if it got picked up.
still running on 1.15.2 since thats where most mods are, might be fixed in the snapshots.

**Comment by doctor4t** [comment]
Seems to happen with all fluids
