### ISSUE TITLE
It will cause too much noise sometimes

### ISSUE THREAD

**Issue by linzexin022** [Ladysnake/Nomad-Books#18]
Hi there, I think this mod causes too much sound when building and breaking small camps, which is a bit annoying. The server even warns that “Maximum sound pool size 247 reached”， “Failed to create new sound handle”. That's because it breaks too many kelps in water and too many grass on the ground at the same time while building camps, and breaking too many noisy blocks in that camp. Don't know if you can solve this problems. May you have a nice day!

**Comment by doctor4t** [comment]
First: Yes I can do something, and I will most likely add a configuration option to just get rid of the blocks and not actually break them.
Second: Thanks for being polite, appreciate it, may you have a nice day too!
