### ISSUE TITLE
game crashes upon loading 

### ISSUE THREAD

**Issue by peanutinky** [Ladysnake/Nomad-Books#26]
i downloaded the 1.16.1 0.5.5 and it crashes upon loading is there a fix for this or is it a misconception that its not for 1.16.1 but for 1.16.2. i'm confused because the file says that its for 1.16.1 and that there was an update version to 1.16.2

**Comment by doctor4t** [comment]
It is indeed for 1.16.2, they were incorrectly marked but now that is fixed. If you don't know what version it is for, the changelog will always be right!
