### ISSUE TITLE
[1.16.3] NPE on attempting to pickup a Nomad Books camp containting a Waystone

### ISSUE THREAD

**Issue by Reveter** [Ladysnake/Nomad-Books#30]
Attempting to pick up a camp from Nomad Books with a Waystone within the area prevents the camp from properly being removed, and prints a stacktrace to console. Possible dupe bug as the camp can still be deployed from the book despite the original not being removed.

[https://gist.github.com/ProsperCraft/f91671463731090b7e9d4414b7f52640](url)

**Comment by ProsperCraft** [comment]
This is funny, I came to report the same bug- here is a video of it happening-
https://youtu.be/N00VEwQSYvw

**Comment by ZestyBlaze** [comment]
Hiya sadly we are no longer supporting version 1.16, we now only will be providing updates and fixes to versions 1.18 and later!
