### ISSUE TITLE
1.16.5 Nomad book copying a Building

### ISSUE THREAD

**Issue by TheCyb0rgW0j3k** [Ladysnake/Nomad-Books#33]
I created a large nomad book because I wanted to make a movable base. When I deploy the base nothing out of ordinary happens, but when I'm retrieving the base it bugs out, it is in fact picked up but it also leave a large chunk of base copied but corrupted.
![nomadbook](https://user-images.githubusercontent.com/87224828/125157211-da95d400-e169-11eb-8005-920aa0a918b2.png)
![nomadbooks2](https://user-images.githubusercontent.com/87224828/125157213-dcf82e00-e169-11eb-921c-145886c0f500.png)
I uploaded 2 pictures which show what nomad book I'm using and the copied bases. If you need something more like a Video I can gladly provide one.
Sincerly Cyb0rgW0j3k

**Comment by Pyrofab** [comment]
Thanks for the report ! Could you also give your latest.log file after this happens ?

**Comment by TheCyb0rgW0j3k** [comment]
[latest.log](https://github.com/Ladysnake/Nomad-Books/files/6794912/latest.log)
Here

**Comment by TheCyb0rgW0j3k** [comment]
Although I should add that it happened on a server.

**Comment by TheCyb0rgW0j3k** [comment]
I've done some testing and I found out that blocks from mod called ,,Conjuring" are causing this. With them in a nomad book a part or entirety of nomad book (depends on how many blocks from Conjuring there are) are being copied.

**Comment by ZestyBlaze** [comment]
Hiya sadly we are no longer supporting version 1.16, we now only will be providing updates and fixes to versions 1.18 and later!
