### ISSUE TITLE
1.17?

### ISSUE THREAD

**Issue by Monster-Zer0** [Ladysnake/Nomad-Books#34]
Sounds like an amazing mod for my exploration based mod pack I am making. is there perhaps any plans for a 1.17 version?

**Comment by doctor4t** [comment]
Up to now there wasn't, as it was less popular than a newer alternative. Might bring it back, I'll look into it when I have time.

**Comment by ZestyBlaze** [comment]
Nomad Books has been updated to 1.18, this is the newest version that will be supported from!
