### ISSUE TITLE
1.18 launch error

### ISSUE THREAD

**Issue by Finlye** [Ladysnake/Nomad-Books#35]
[nomadic books crash.txt](https://github.com/Ladysnake/Nomad-Books/files/8749721/nomadic.books.crash.txt)

upon trying to launch minecraft with the 1.18 version it crashes back to the launcher with exit code 1 even when its the only mod installed.
i am trying to run this viaCurseforge app so i do not know if that is a contributer to this.

**Comment by ZestyBlaze** [comment]
Would you mind sending the latest.log as well for the startup of this please? This is a very strange error as I've not been getting this during testing
If you can also send the following information:
Minecraft Version:
Exact name of the file you are using:
List of all the mods you have installed (Look in the mods folder):

**Comment by Finlye** [comment]
1.18.1
nomadbooks-1.18-1.0.1
[latest.log](https://github.com/Ladysnake/Nomad-Books/files/8775243/latest.log)
the only other none disabled mod is:
fabric-api-0.46.6+1.18

if you want all mods im running, ill assemble a list and get that to ya.

**Comment by ZestyBlaze** [comment]
Hang on I might have figured this out. Give me a couple mins to test this theory

**Comment by ZestyBlaze** [comment]
Would you mind trying FAPI and nomad in 1.18.2 please?

**Comment by Finlye** [comment]
it runs, so im assuming its with 1.18.1 specifically then

**Comment by ZestyBlaze** [comment]
Seems like it, I don't know why that is, I'll fix the versions on CF to fix this, sorry for causing a problem
Seems like one of the resources that the mod uses changed between 1.18.1 and 1.18.2 which causes it to break
